#!/bin/sh
# Remove the `sysinfo` alias on package removal.
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -L /usr/bin/sysinfo ]; then
        rm -f /usr/bin/sysinfo || true
    fi
fi
exit 0
